spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://localhost/restaurant_advisor
    username: postgres
    password: 1234
  data:
    rest:
      base-path: /api
  security:
    filter:
      order: 10

logging:
  level:
    root: WARN
    com.example.restaurant_advisor_react: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

jwt.secret: 987ghgfyf*Yt87tFF089uyHgf9TfgF!&909u79ygUVLJH987y89yguyfgr&YHG*0fS
jwt.ExpirationMs: 2592000000

application-description: Service designed to assist people in choosing a restaurant
application-version: 1.0.0